workflows:
  android_release:
    name: Android Release (Notifications)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: 3.24.0

    scripts:
      # 1) Android/iOS klasörleri yoksa oluştur
      - name: Ensure project structure
        script: |
          if [ ! -d "android" ]; then
            flutter create .
          fi

      # 2) Manifest'i yaz (izin + receiver + v2 embedding meta-data)
      - name: Write AndroidManifest.xml
        script: |
          mkdir -p android/app/src/main
          cat > android/app/src/main/AndroidManifest.xml <<'EOF'
          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
              package="com.example.maestroveteriner_maker">

              <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>

              <application
                  android:label="Ramazan Planner"
                  android:icon="@mipmap/ic_launcher">

                  <!-- v2 embedding bildirimi -->
                  <meta-data android:name="flutterEmbedding" android:value="2"/>

                  <!-- Boot sonrası planlanan bildirimleri geri kur -->
                  <receiver
                      android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver"
                      android:exported="false">
                    <intent-filter>
                      <action android:name="android.intent.action.BOOT_COMPLETED"/>
                      <action android:name="android.intent.action.MY_PACKAGE_REPLACED"/>
                    </intent-filter>
                  </receiver>

                  <activity
                      android:name=".MainActivity"
                      android:exported="true"
                      android:launchMode="singleTop"
                      android:theme="@style/LaunchTheme"
                      android:configChanges="keyboard|keyboardHidden|orientation|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
                      android:hardwareAccelerated="true"
                      android:windowSoftInputMode="adjustResize">
                      <intent-filter>
                        <action android:name="android.intent.action.MAIN"/>
                        <category android:name="android.intent.category.LAUNCHER"/>
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOF

      # 3) minSdkVersion >= 21 (bildirim paketi için gerekli)
      - name: Ensure minSdkVersion >= 21
        script: |
          if [ -f android/app/build.gradle ]; then
            sed -i.bak 's/minSdkVersion [0-9][0-9]*/minSdkVersion 21/' android/app/build.gradle || true
          fi

      # 4) Temizlik ve bağımlılıklar
      - name: Flutter clean
        script: flutter clean
      - name: Get dependencies
        script: flutter pub get

      # 5) (Emniyet) MainActivity v2 embedding'e işaret ediyor mu?
      - name: Ensure MainActivity uses v2 embedding
        script: |
          FILE_KT=$(grep -Rsl "class MainActivity" android/app/src/main/kotlin || true)
          if [ -n "$FILE_KT" ]; then
            sed -i.bak 's/io.flutter.app.FlutterActivity/io.flutter.embedding.android.FlutterActivity/g' "$FILE_KT" || true
          fi

      # 6) APK üret
      - name: Build release APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
