workflows:
  android_release:
    name: Android Release (Notifications)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: 3.24.0

    scripts:
      # 1) Proje iskeleti yoksa üret (android/ klasörü dahil)
      - name: Ensure project structure
        script: |
          if [ ! -d "android" ]; then
            flutter create .
          fi

      # 2) AndroidManifest.xml'i yaz (izin + boot receiver + embedding v2 meta-data)
      - name: Write AndroidManifest.xml
        script: |
          mkdir -p android/app/src/main
          cat > android/app/src/main/AndroidManifest.xml << 'EOF'
          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
              package="com.example.maestroveteriner_maker">

              <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>

              <application
                  android:label="Ramazan Planner"
                  android:icon="@mipmap/ic_launcher">

                  <!-- ZORUNLU: v2 embedding bildirimi -
