workflows:
  debug_android:
    name: Debug Android APK
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Ensure Android folder exists
        script: |
          if [ ! -d "android" ]; then
            flutter create . --platforms=android
          fi
          flutter pub get
      - name: Build debug APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
